// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyBackendAPI.Data;

#nullable disable

namespace MyBackendAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260929175742_AddAuthAndProjectAudit")]
    partial class AddAuthAndProjectAudit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("MonitoringReview", b =>
                {
                    b.Property<int>("MonitoringReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MonitoringReviewId"));

                    b.Property<string>("KickoffBrief")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("KickoffDate")
                        .HasColumnType("date");

                    b.Property<byte[]>("KickoffMomFile")
                        .HasColumnType("LONGBLOB");

                    b.Property<byte[]>("KickoffPptFileName")
                        .HasColumnType("LONGBLOB");

                    b.Property<string>("PmrcBrief")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("PmrcDate")
                        .HasColumnType("date");

                    b.Property<byte[]>("PmrcMomFile")
                        .HasColumnType("LONGBLOB");

                    b.Property<byte[]>("PmrcPptFileName")
                        .HasColumnType("LONGBLOB");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("datetime");

                    b.HasKey("MonitoringReviewId");

                    b.HasIndex("ProjectId")
                        .IsUnique();

                    b.ToTable("monitoringreview", (string)null);
                });

            modelBuilder.Entity("MyBackendAPI.Models.PreProject", b =>
                {
                    b.Property<int>("PreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PreId"));

                    b.Property<string>("Capital")
                        .HasColumnType("longtext");

                    b.Property<string>("CcmApproval")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("CcmDate")
                        .HasColumnType("date");

                    b.Property<byte[]>("CcmMinutesFile")
                        .HasColumnType("longblob");

                    b.Property<string>("CecBrief")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("CecDate")
                        .HasColumnType("date");

                    b.Property<byte[]>("CecMinutesFile")
                        .HasColumnType("longblob");

                    b.Property<string>("CostBrief")
                        .HasColumnType("longtext");

                    b.Property<byte[]>("CostFile")
                        .HasColumnType("longblob");

                    b.Property<byte[]>("CouncilFile")
                        .HasColumnType("longblob");

                    b.Property<DateTime>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("DmcBrief")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("DmcDate")
                        .HasColumnType("date");

                    b.Property<byte[]>("DmcMinutesFile")
                        .HasColumnType("longblob");

                    b.Property<string>("DraftBrief")
                        .HasColumnType("longtext");

                    b.Property<string>("DurationBrief")
                        .HasColumnType("longtext");

                    b.Property<byte[]>("DurationEstFile")
                        .HasColumnType("longblob");

                    b.Property<byte[]>("ExecutiveSumFile")
                        .HasColumnType("longblob");

                    b.Property<string>("ExecutiveSummary")
                        .HasColumnType("longtext");

                    b.Property<string>("FeDetails")
                        .HasColumnType("longtext");

                    b.Property<string>("IcDetails")
                        .HasColumnType("longtext");

                    b.Property<string>("ManagementApproval")
                        .HasColumnType("longtext");

                    b.Property<string>("ManagementCounBrief")
                        .HasColumnType("longtext");

                    b.Property<byte[]>("ManagementMinutesFile")
                        .HasColumnType("longblob");

                    b.Property<byte[]>("MinutesFile")
                        .HasColumnType("longblob");

                    b.Property<string>("ObjectiveBrief")
                        .HasColumnType("longtext");

                    b.Property<byte[]>("ObjectiveFile")
                        .HasColumnType("longblob");

                    b.Property<string>("ParticipatingLabs")
                        .HasColumnType("longtext");

                    b.Property<string>("PdrBrief")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("PdrDate")
                        .HasColumnType("date");

                    b.Property<byte[]>("PdrFile")
                        .HasColumnType("longblob");

                    b.Property<byte[]>("PdrMinutesFile")
                        .HasColumnType("longblob");

                    b.Property<string>("PrcApproval")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("PrcDate")
                        .HasColumnType("date");

                    b.Property<byte[]>("PrcMinutesFile")
                        .HasColumnType("longblob");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("ReDetails")
                        .HasColumnType("longtext");

                    b.Property<string>("Revenue")
                        .HasColumnType("longtext");

                    b.Property<string>("ScopeBrief")
                        .HasColumnType("longtext");

                    b.Property<byte[]>("ScopeFile")
                        .HasColumnType("longblob");

                    b.Property<string>("SosBrief")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("SosDate")
                        .HasColumnType("date");

                    b.Property<byte[]>("SosMinutesFile")
                        .HasColumnType("longblob");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("TiecBrief")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("TiecDate")
                        .HasColumnType("date");

                    b.Property<byte[]>("TiecMinutesFile")
                        .HasColumnType("longblob");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("User")
                        .HasColumnType("longtext");

                    b.Property<byte[]>("UserFile")
                        .HasColumnType("longblob");

                    b.HasKey("PreId");

                    b.HasIndex("ProjectId")
                        .IsUnique();

                    b.ToTable("pre_project", (string)null);
                });

            modelBuilder.Entity("MyBackendAPI.Models.Project", b =>
                {
                    b.Property<int>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ProjectId"));

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("date");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("ProjectId");

                    b.ToTable("projects", (string)null);
                });

            modelBuilder.Entity("MyBackendAPI.Models.ProjectClosure", b =>
                {
                    b.Property<int>("ProjectClosureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ProjectClosureId"));

                    b.Property<byte[]>("AcFile")
                        .HasColumnType("longblob");

                    b.Property<DateTime?>("ClDate")
                        .HasColumnType("date");

                    b.Property<byte[]>("ClFile")
                        .HasColumnType("longblob");

                    b.Property<string>("IdcmApproval")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("IdcmDate")
                        .HasColumnType("date");

                    b.Property<byte[]>("IdcmFile")
                        .HasColumnType("longblob");

                    b.Property<byte[]>("IdcmMomFile")
                        .HasColumnType("longblob");

                    b.Property<string>("IdcmRecommendation")
                        .HasColumnType("longtext");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("TcrApproval")
                        .HasColumnType("longtext");

                    b.Property<byte[]>("TcrFile")
                        .HasColumnType("longblob");

                    b.Property<string>("TcrReport")
                        .HasColumnType("longtext");

                    b.HasKey("ProjectClosureId");

                    b.HasIndex("ProjectId")
                        .IsUnique();

                    b.ToTable("project_closure", (string)null);
                });

            modelBuilder.Entity("MyBackendAPI.Models.ProjectSanction", b =>
                {
                    b.Property<int>("ProjectSanctionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ProjectSanctionId"));

                    b.Property<string>("Category")
                        .HasColumnType("longtext");

                    b.Property<string>("CorrigendumDescription")
                        .HasColumnType("longtext");

                    b.Property<byte[]>("CorrigendumFile")
                        .HasColumnType("longblob");

                    b.Property<string>("DeliverableDetails")
                        .HasColumnType("longtext");

                    b.Property<byte[]>("DeliverableFile")
                        .HasColumnType("longblob");

                    b.Property<string>("EbmBrief")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("EbmDate")
                        .HasColumnType("date");

                    b.Property<byte[]>("EbmMomFile")
                        .HasColumnType("longblob");

                    b.Property<byte[]>("EbmPptFile")
                        .HasColumnType("longblob");

                    b.Property<string>("ParticipatingLabName")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("PdcDate")
                        .HasColumnType("date");

                    b.Property<string>("PdcDetails")
                        .HasColumnType("longtext");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("SanctionApproval")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("SanctionDate")
                        .HasColumnType("date");

                    b.Property<string>("SanctionDescription")
                        .HasColumnType("longtext");

                    b.Property<byte[]>("SanctionLetterFile")
                        .HasColumnType("longblob");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("datetime");

                    b.HasKey("ProjectSanctionId");

                    b.HasIndex("ProjectId")
                        .IsUnique();

                    b.ToTable("project_sanction", (string)null);
                });

            modelBuilder.Entity("MyBackendAPI.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("MonitoringReview", b =>
                {
                    b.HasOne("MyBackendAPI.Models.Project", "Project")
                        .WithOne("MonitoringReview")
                        .HasForeignKey("MonitoringReview", "ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("MyBackendAPI.Models.PreProject", b =>
                {
                    b.HasOne("MyBackendAPI.Models.Project", "Project")
                        .WithOne("PreProject")
                        .HasForeignKey("MyBackendAPI.Models.PreProject", "ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("MyBackendAPI.Models.ProjectClosure", b =>
                {
                    b.HasOne("MyBackendAPI.Models.Project", "Project")
                        .WithOne("ProjectClosure")
                        .HasForeignKey("MyBackendAPI.Models.ProjectClosure", "ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("MyBackendAPI.Models.ProjectSanction", b =>
                {
                    b.HasOne("MyBackendAPI.Models.Project", "Project")
                        .WithOne("ProjectSanction")
                        .HasForeignKey("MyBackendAPI.Models.ProjectSanction", "ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("MyBackendAPI.Models.Project", b =>
                {
                    b.Navigation("MonitoringReview");

                    b.Navigation("PreProject");

                    b.Navigation("ProjectClosure");

                    b.Navigation("ProjectSanction");
                });
#pragma warning restore 612, 618
        }
    }
}
